[package]
name = "c8rs"
version = "0.1.0"
authors = ["Pablo Pérez Rodríguez <pablo@pabl.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
